const COLUMN_LABELS: Record<string, string> = {
  // Dados gerais
  uf: 'UF',
  UF: 'UF',
  nome: 'Nome',
  Nome: 'Nome',
  cpf: 'CPF',
  CPF: 'CPF',
  cnpj: 'CNPJ',
  CNPJ: 'CNPJ',
  cro: 'CRO',
  CRO: 'CRO',
  email: 'E-mail',
  Email: 'E-mail',
  EMAIL: 'E-mail',
  telefone: 'Telefone',
  id_registro: 'ID Registro',
  IdRegistro: 'ID Registro',

  // Profissional
  categoria: 'Categoria',
  Categoria: 'Categoria',
  CATEGORIA: 'Categoria',
  inscricao: 'Inscrição',
  Inscricao: 'Inscrição',
  INSCRICAO: 'Inscrição',
  situacao: 'Situação',
  Situacao: 'Situação',
  SITUACAO: 'Situação',
  detalhe: 'Detalhe',
  Detalhe: 'Detalhe',
  tipo_inscricao: 'Tipo Inscrição',
  TipoInscricao: 'Tipo Inscrição',
  Tipo_Inscricao: 'Tipo Inscrição',
  TIPO_INSCRICAO: 'Tipo Inscrição',
  situacao_financeira: 'Situação Financeira',
  SituacaoFinanceira: 'Situação Financeira',
  detalhe_situacao: 'Detalhe Situação',
  DetalheSituacao: 'Detalhe Situação',
  DETALHE_SITUACAO: 'Detalhe Situação',

  // Dados pessoais
  data_nascimento: 'Data Nascimento',
  DATA_NASCIMENTO: 'Data Nascimento',
  genero: 'Gênero',
  nome_mae: 'Nome da Mãe',
  nome_pai: 'Nome do Pai',
  estado_civil: 'Estado Civil',
  nacionalidade: 'Nacionalidade',
  naturalidade: 'Naturalidade',
  profissional: 'Profissional',
  PROFISSIONAL: 'Profissional',

  // Endereço
  logradouro: 'Logradouro',
  numero: 'Número',
  complemento: 'Complemento',
  bairro: 'Bairro',
  municipio: 'Município',
  cep: 'CEP',

  // Empresa
  razao_social: 'Razão Social',
  nome_fantasia: 'Nome Fantasia',
  NomeRazaoSocial: 'Nome/Razão Social',
  CPFCNPJ: 'CPF/CNPJ',
  CpfCnpj: 'CPF/CNPJ',
  Razao_Social: 'Razão Social',
  Nome_Fantasia: 'Nome Fantasia',

  // Formação
  instituicao: 'Instituição',
  InstituicaoDeEnsino: 'Instituição de Ensino',
  curso: 'Curso',
  Curso: 'Curso',
  DataDeColacao: 'Data de Colação',
  DataDeConclusao: 'Data de Conclusão',
  Data_Colacao_Grau: 'Data Colação de Grau',
  Data_Conclusao: 'Data Conclusão',

  // Totais e quantidades
  total: 'Total',
  Total: 'Total',
  TOTAL: 'Total',
  quantidade: 'Quantidade',
  Quantidade: 'Quantidade',
  total_geral: 'Total Geral',
  Total_geral: 'Total Geral',

  // Relatórios Financeiros
  Convenio_BB: 'Convênio BB',
  Codigo_Convenio_BB: 'Código Convênio BB',
  Total_Tarifa_Liquidacao: 'Total Tarifa Liquidação',
  Total_Arrecadado: 'Total Arrecadado',
  TipoTarifa: 'Tipo Tarifa',
  Total_Tarifa: 'Total Tarifa',
  Total_Pago: 'Total Pago',
  Total_Pagamento: 'Total Pagamento',
  Forma_Pagamento: 'Forma Pagamento',
  Data_Credito: 'Data Crédito',
  Valor_Bruto: 'Valor Bruto',
  Valor_CRO: 'Valor CRO',
  Tarifa_Cartao: 'Tarifa Cartão',
  Split_Federal: 'Split Federal',

  // Processos / Especialidade
  NumeroProcesso: 'Número Processo',
  numero_processo: 'Número Processo',
  Classificacao: 'Classificação',
  classificacao: 'Classificação',
  EtapaProcesso: 'Etapa Processo',
  Andamento: 'Andamento',
  DataAndamento: 'Data Andamento',
  data_andamento: 'Data Andamento',
  DiasDesdeAndamento: 'Dias Desde Andamento',

  // Auditorias
  DataSituacao: 'Data Situação',
  Data_Situacao_Registro_Atual: 'Data Situação Registro Atual',
  Validade_Provisoria: 'Validade Provisória',

  // Fiscalização
  TotalAtivos: 'Total Ativos',
  AnoProfAtivos: 'Ano Prof. Ativos',
  QtdFiscalizacoes: 'Qtd. Fiscalizações',
  AnoFiscalizacoes: 'Ano Fiscalizações',
  PercentualFiscalizacoes: 'Percentual Fiscalizações',
  FiscOnline: 'Fisc. Online',
  FiscProativas: 'Fisc. Proativas',
  FiscReativas: 'Fisc. Reativas',
  FiscNaoInformado: 'Fisc. Não Informado',
  FiscExercicioIlegal: 'Fisc. Exercício Ilegal',
  Notificacoes: 'Notificações',
  FiscComTermo: 'Fisc. com Termo',
  Irregularidades: 'Irregularidades',
  Denuncias: 'Denúncias',
  Fiscal: 'Fiscal',
  Pessoa: 'Pessoa',
  grupo: 'Grupo',
  subgrupo: 'Subgrupo',
  ANO: 'Ano',
  Ano: 'Ano',

  // Estatística
  REGIAO: 'Região',
  POPULACAO: 'População',
  CD_FEM: 'CD Fem.',
  CD_MAS: 'CD Masc.',
  APD_FEM: 'APD Fem.',
  APD_MAS: 'APD Masc.',
  TPD_FEM: 'TPD Fem.',
  TPD_MAS: 'TPD Masc.',
  ASB_FEM: 'ASB Fem.',
  ASB_MAS: 'ASB Masc.',
  TSB_FEM: 'TSB Fem.',
  TSB_MAS: 'TSB Masc.',
  TOT_FEM: 'Total Fem.',
  TOT_MAS: 'Total Masc.',
  TOT_BRASIL: 'Total Brasil',
  ANO_REGISTRO: 'Ano Registro',
  TOT_CD_FEM: 'Total CD Fem.',
  TOT_CD_MAS: 'Total CD Masc.',
  TOT_APD_FEM: 'Total APD Fem.',
  TOT_APD_MAS: 'Total APD Masc.',
  TOT_TPD_FEM: 'Total TPD Fem.',
  TOT_TPD_MAS: 'Total TPD Masc.',
  TOT_ASB_FEM: 'Total ASB Fem.',
  TOT_ASB_MAS: 'Total ASB Masc.',
  TOT_TSB_FEM: 'Total TSB Fem.',
  TOT_TSB_MAS: 'Total TSB Masc.',
  TOTAL_PROF_FEM: 'Total Prof. Fem.',
  TOTAL_PROF_MAS: 'Total Prof. Masc.',
  TOTAL_GERAL: 'Total Geral',
  FAIXA_ETARIA: 'Faixa Etária',
  TOTAL_FEM: 'Total Fem.',
  TOTAL_MAS: 'Total Masc.',
  TOTAL_CRO: 'Total CRO',
  TOTAL_ANO: 'Total Ano',
  especializacao: 'Especialização',
  Especialidade: 'Especialidade',
  Masculino: 'Masculino',
  Feminino: 'Feminino',
  Idade: 'Idade',
  Ate_Ano: 'Até Ano',
  ECIPO: 'ECIPO',
  EPAO: 'EPAO',
  LB: 'LB',
  APD: 'APD',
  ASB: 'ASB',
  CD: 'CD',
  TPD: 'TPD',
  TSB: 'TSB',

  // Identidade
  CFO_ID: 'CFO ID',
  PRODUZIDAS: 'Produzidas',
  PERC_PROD: '% Produzidas',
  POSTADAS: 'Postadas',
  PERC_POST: '% Postadas',
  ENTREGUES: 'Entregues',
  PERC_ENTR: '% Entregues',
  DEVOLVIDAS: 'Devolvidas',
  PERC_DEV: '% Devolvidas',
  EM_TRANSITO: 'Em Trânsito',
  PERC_TRAM: '% Em Trânsito',
  TOTAL_CD: 'Total CD',
  TOTAL_TSB: 'Total TSB',
  TOTAL_ASB: 'Total ASB',
  TOTAL_APD: 'Total APD',
  TOTAL_TPD: 'Total TPD',
  MES: 'Mês',
  DATA_EMISSAO_ID: 'Data Emissão ID',
  STATUS: 'Status',
  ar: 'AR',
  data_despacho: 'Data Despacho',
  cro_uf: 'CRO/UF',
  consta_api: 'Consta API',
  usuario_adicionou: 'Usuário Adicionou',
  motivo: 'Motivo',

  // Prescrição
  tipo: 'Tipo',
  id: 'ID',
  psc: 'PSC',
  paciente_nome: 'Nome Paciente',
  paciente_cpf: 'CPF Paciente',
  cd_nome: 'Nome CD',
  insc: 'Inscrição',
  data: 'Data',
  data_prescricao: 'Data Prescrição',
  SiglaCRO: 'Sigla CRO',
  SiglaCategoria: 'Sigla Categoria',
  DataInscricaoCRO: 'Data Inscrição CRO',
  DataSituacaoAtual: 'Data Situação Atual',

  // Eleições
  NOME_COMPLETO: 'Nome Completo',
  ADIMPLENCIA: 'Adimplência',
  VOTANTE: 'Votante',
  DEVEDOR: 'Devedor',
  MOTIVO_NAO_VOTANTE: 'Motivo Não Votante',
  CELULAR_ATUALIZADO: 'Celular Atualizado',
  DATA_INSCRICAO_CRO: 'Data Inscrição CRO',
  DATA_REGISTRO_CFO: 'Data Registro CFO',
  total_ativos: 'Total Ativos',
  total_desativados: 'Total Desativados',
  total_votantes: 'Total Votantes',
  votantes_devedores: 'Votantes Devedores',
  votantes_adimplentes: 'Votantes Adimplentes',
  DATA_DIRETORIA_CRO: 'Data Diretoria CRO',
  TIPO_EMAIL_UTILIZADO: 'Tipo E-mail Utilizado',
  OUTROS_EMAILS: 'Outros E-mails',
  OUTROS_TELEFONES: 'Outros Telefones',
  DATA_GERACAO: 'Data Geração',
  HORA_GERACAO: 'Hora Geração',

  // Tabelas centralizadas (IES)
  Regional: 'Regional',
  Ativo: 'Ativo',
  Inscricao_Estadual: 'Inscrição Estadual',
  Sigla: 'Sigla',
  Natureza_Juridica: 'Natureza Jurídica',
  Codigo: 'Código',
  Codigo_Integracao_Federal: 'Código Integração Federal',
  Codigo_IE: 'Código IE',
  Reitor: 'Reitor',
  Cursos: 'Cursos',
  Especialidades: 'Especialidades',
  Campus: 'Campus',
  Coordenadores_qtd: 'Qtd. Coordenadores',
  Observacao: 'Observação',
  Coordenadores: 'Coordenadores',

  // Adimplência
  Anuidades: 'Anuidades',
  Pago: 'Pago',
  Perc_Adimplente: '% Adimplente',
  Perc_Inadimplente: '% Inadimplente',
  Nao_Pago: 'Não Pago',
  Pago_a_Menor: 'Pago a Menor',
  Valor_Devido_Nao_Pago: 'Valor Devido Não Pago',
  Valor_Devido_Pago_a_Menor: 'Valor Devido Pago a Menor',
  Valor_Pago: 'Valor Pago',

  // Auditoria multi-CRO
  NOME_1: 'Nome 1',
  CRO_1: 'CRO 1',
  CATE_1: 'Categoria 1',
  INSC_1: 'Inscrição 1',
  TIPO_INSCRICAO_1: 'Tipo Inscrição 1',
  SITUACAO_1: 'Situação 1',
  DETALHE_1: 'Detalhe 1',
  DATA_INSC_1: 'Data Inscrição 1',
  NOME_2: 'Nome 2',
  CRO_2: 'CRO 2',
  CATE_2: 'Categoria 2',
  INSC_2: 'Inscrição 2',
  TIPO_INSCRICAO_2: 'Tipo Inscrição 2',
  SITUACAO_2: 'Situação 2',
  DETALHE_2: 'Detalhe 2',
  DATA_INSC_2: 'Data Inscrição 2',

  // RFB / Log
  tipo_consulta: 'Tipo Consulta',
  documento: 'Documento',
  documento_consultado: 'Documento Consultado',
  existe_base_cfo: 'Existe Base CFO',
  inscricao_cfo: 'Inscrição CFO',
  nome_cfo: 'Nome CFO',
  cro_cfo: 'CRO CFO',
  situacao_cfo: 'Situação CFO',
  sucesso: 'Sucesso',
  mensagem_erro: 'Mensagem Erro',
  tempo_resposta_ms: 'Tempo Resposta (ms)',
  ip_origem: 'IP Origem',
  data_hora: 'Data/Hora',
  usuario_id: 'ID Usuário',
  usuario_nome: 'Nome Usuário',
  usuario_email: 'E-mail Usuário',
  usuario_grupo: 'Grupo Usuário',

  // Dados Abertos
  Contrato: 'Contrato',
  Convenio: 'Convênio',
  Licitacao: 'Licitação',
  Aquisicao: 'Aquisição',
  Descricao: 'Descrição',
  Numero: 'Número',
  Situacao_Contrato: 'Situação Contrato',
  Vigencia: 'Vigência',
  Valor: 'Valor',
  DataPublicacao: 'Data Publicação',
};

export function formatColumnLabel(key: string): string {
  if (COLUMN_LABELS[key]) return COLUMN_LABELS[key];
  return key
    .replace(/_/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/^./, c => c.toUpperCase());
}
